### ISSUE TITLE
ecs.DescribeVolumes missing

### ISSUE THREAD

**Issue by BusyOppo** [volcengine/volcengine-go-sdk#61]
.

**Comment by xuyaming0800** [comment]
@BusyOppo 
Thank you for using our SDK tools and make a suggestion ！
For this issue, because on our service gateway, ecs and ebs is two different service with name ecs and storage_ebs,
and our sdk service package only support one service name in one package, so we split them to two different package.

感谢使用我们的SDK和提出建议
在我们的服务网关上，虚机和云盘是两个不同的服务注册，注册的名字分别是ecs和storage_ebs，并且我们的SDK的设计是按照服务名称做隔离的，一个服务包下面就是代表唯一的服务名，所以我们会拆成两个
